
DROP TABLE IF EXISTS TB_COMENTARIO;

CREATE TABLE IF NOT EXISTS TB_COMENTARIO (
    ID_COMENTARIO INT AUTO_INCREMENT PRIMARY KEY,
    ID_FILME INT NOT NULL,
    EMAIL_USUARIO VARCHAR(255) NOT NULL,
    NOME_USUARIO VARCHAR(255) NOT NULL,
    TEXTO TEXT NOT NULL,
    DATA_COMENTARIO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    LIKES INT DEFAULT 0,
    DISLIKES INT DEFAULT 0,
    AVALIACAO INT DEFAULT 0,
    FOREIGN KEY (ID_FILME) REFERENCES TB_FILME(ID_FILME)
);

-- Índice para otimizar buscas por filme
CREATE INDEX IF NOT EXISTS IDX_COMENTARIO_FILME ON TB_COMENTARIO(ID_FILME);

-- Índice para buscas por usuário
CREATE INDEX IF NOT EXISTS IDX_COMENTARIO_USUARIO ON TB_COMENTARIO(EMAIL_USUARIO);
